// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonBackend.Data;

#nullable disable

namespace MonBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250707182816_AddTables")]
    partial class AddTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonBackend.Models.DemandeCongé", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDemande")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("TypeCongeId")
                        .HasColumnType("int");

                    b.Property<int>("TypeCongéId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeCongéId");

                    b.HasIndex("UserId");

                    b.ToTable("DemandesCongés");
                });

            modelBuilder.Entity("MonBackend.Models.JourFerie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JourFeries");
                });

            modelBuilder.Entity("MonBackend.Models.LigneNoteFrais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistanceKm")
                        .HasColumnType("int");

                    b.Property<string>("JustificatifPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NoteDeFraisId")
                        .HasColumnType("int");

                    b.Property<int?>("TarifKmId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NoteDeFraisId");

                    b.HasIndex("TarifKmId");

                    b.ToTable("LignesNotesFrais");
                });

            modelBuilder.Entity("MonBackend.Models.NoteDeFrais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateSoumission")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProjetId")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId");

                    b.HasIndex("UserId");

                    b.ToTable("NotesDeFrais");
                });

            modelBuilder.Entity("MonBackend.Models.Projet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projets");
                });

            modelBuilder.Entity("MonBackend.Models.TarifKm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategorieVehicule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TarifParKm")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TarifsKm");
                });

            modelBuilder.Entity("MonBackend.Models.TypeCongé", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TypeCongés");
                });

            modelBuilder.Entity("MonBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("SoldeCongés")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MonBackend.Models.DemandeCongé", b =>
                {
                    b.HasOne("MonBackend.Models.TypeCongé", "TypeCongé")
                        .WithMany()
                        .HasForeignKey("TypeCongéId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonBackend.Models.User", "Employe")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("TypeCongé");
                });

            modelBuilder.Entity("MonBackend.Models.LigneNoteFrais", b =>
                {
                    b.HasOne("MonBackend.Models.NoteDeFrais", "NoteDeFrais")
                        .WithMany("Lignes")
                        .HasForeignKey("NoteDeFraisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonBackend.Models.TarifKm", "TarifKm")
                        .WithMany()
                        .HasForeignKey("TarifKmId");

                    b.Navigation("NoteDeFrais");

                    b.Navigation("TarifKm");
                });

            modelBuilder.Entity("MonBackend.Models.NoteDeFrais", b =>
                {
                    b.HasOne("MonBackend.Models.Projet", "Projet")
                        .WithMany("NotesDeFrais")
                        .HasForeignKey("ProjetId");

                    b.HasOne("MonBackend.Models.User", "Employe")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("MonBackend.Models.User", b =>
                {
                    b.HasOne("MonBackend.Models.User", "Manager")
                        .WithMany("Subordonnes")
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("MonBackend.Models.NoteDeFrais", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("MonBackend.Models.Projet", b =>
                {
                    b.Navigation("NotesDeFrais");
                });

            modelBuilder.Entity("MonBackend.Models.User", b =>
                {
                    b.Navigation("Subordonnes");
                });
#pragma warning restore 612, 618
        }
    }
}
